### ISSUE TITLE
My EXCC coins gone

### ISSUE THREAD

**Issue by SaintLuca** [EXCCoin/exilibrium#14]
Intro:
I have 2 wallet at Exchangecoin Wallet (desktop wallet)
When EXCC give new update, they told you to export & import to a new desktop wallet because the old desktop wallet will be disabled.
Problem:
The 1st wallet succeed imported and still has the balances.
The 2nd wallet succeed imported BUT the balances is GONE. I have tried many ways: import with json multiple times & import with 12 words. Still can't see my balances.
I try download the history transaction of 2nd wallet but I didn't see any withdrawal (that mean i'm not hacked by someone, right?) So where's the EXCC coins gone??

Please helppp...
Sorry for my troubled english.

**Comment by jwjanus** [comment]
Hi, thanks for creating an issue. First things first, can you please check if your 2nd wallet address/addresses have expected balances? you can check them on the [explorer](https://explorer.excc.co)
Second thing, just to clarify, your second wallet also has mnemonic, or it is single private key (single address wallet)? And third question, if applicable, are the mnemonic words for second wallet in english?

**Comment by SaintLuca** [comment]
Hi, thanks for replying.

First, From what I get from EXCC's support my balance is 0 EXCC (I don't know how to get my own address to check it, they find it for me)
https://explorer2.excc.co/address/22tn3ErASTXzUJctTEQBeF6ZnzGt4gubvEHW

Second, I only know I have those 12 words for backup my wallet, and I dont have any private keys, the truth is I don't really know if I have or not. If I have, where can I find it?

Third, Yes, the 12 words is in english.

Thanks, sorry for my troubled english.

**Comment by jwjanus** [comment]
Explorer is available at https://explorer.excc.co (explorer2 was for the old blockchain). The address you have provided in the link above has balance 0 also on the new blockchain 
https://explorer.excc.co/address/22tn3ErASTXzUJctTEQBeF6ZnzGt4gubvEHW

So, as i understand, you had 2 wallets (meaning -  two 12-word mnemonics), and you used both of them on desktop wallet. Does the old wallet still show balances for both wallets?
Wallets with 12 word mnemonics can have almost infinite number of addresses. What you can try to do is: 
1. In the old wallet - go to  the second wallet that doesn't work in Exilibrium.
2. Copy address for receiving coins (hope it's still possible).
3, Go to Exilibrium, and start the wallet that was imported incorrectly.
4. After launching the wallet go to "Security" section, and then to "Validate Address" tab,
5. Paste the address from the old wallet there, it will tell you if given address comes from this wallet.

Let me know what was the result, so we can investigate further the issue.

**Comment by SaintLuca** [comment]
Hi, I have tried them.

The old desktop wallet still show both wallets' balances.
And I have tried to validate address but it said "Not owned address!"

Here I give you the screenshot from what i done your guide.
What next can I do?

![not owned address](https://user-images.githubusercontent.com/42145232/43903450-afc574c4-9c16-11e8-8999-c571caf47225.PNG)
![not owned address2](https://user-images.githubusercontent.com/42145232/43903453-b03d64de-9c16-11e8-889d-5b12a61e42a1.PNG)
![old wallet](https://user-images.githubusercontent.com/42145232/43903454-b075d198-9c16-11e8-8f61-8e3c1b8ba4ae.PNG)

**Comment by SaintLuca** [comment]
Sorry forget to tell you, I had request once more received address and validate it.
Both address show "not owned address" as the screenshot above.

**Comment by jwjanus** [comment]
This may happen sometimes. What we can try now is this: Go to "Settings Page" and set "Gap limit" to something higher than 20 (could be 1000, if this won't work, try 2000, etc.). After saving, close the wallet, launch again. Now wallet start could take way longer, but there is possibility that this will find address with correct balance.

**Comment by SaintLuca** [comment]
Hi, i have tried it, i try from 1000,2000,....,20000 but still 0 EXCC.
What to do? try again till 100000?

**Comment by SaintLuca** [comment]
I'm trying to find my xPrivKey and restore it, but it come out:
Error: 3 INVALID_ARGUMENT: Invalid WIF-encoded private key: malformed private key

What is that mean?

**Comment by SaintLuca** [comment]
Hello, thanks for the assistance, I have found my EXCC back.
Please close this issue.

**Comment by jwjanus** [comment]
That's great to hear. Sorry for not responding for a long time. Closing.
