### ISSUE TITLE
create wallet failure

### ISSUE THREAD

**Issue by lhszhh131421** [EXCCoin/exilibrium#18]
when I import the key ,I put the create wallet ,but when the new window opened,it is empty,it doesn't action. why?

**Comment by jwjanus** [comment]
Hi, could you describe the issue in more detail? So, after wallet started, and you clicked on "Create New Wallet" you saw empty screen or it happened after clicking on "Import Keys"? You can attach a print screen here (but be careful to remove/blur sensitive data)

**Comment by lhszhh131421** [comment]
After I clicked on "Create New Wallet" ,I saw a empty window.

![_20180809180121](https://user-images.githubusercontent.com/36321409/43892379-52fc108a-9bfe-11e8-9eb6-76622f4500d4.png)
![_20180809180131](https://user-images.githubusercontent.com/36321409/43892384-57d4e780-9bfe-11e8-914b-4e98eebd57a1.png)

**Comment by jwjanus** [comment]
Cool, thanks for providing printscreens. This looks weird. I'd like to ask you to try restoring wallet in a different way: after you click on "Show mnemonic" button it should show your mnemonic words & decoded seed hex. Please copy this hex, go to "Restore Wallet" section (instead of "Import Keys") and in the upper right corner you'll see "Hex" button, click on it, paste your hex to the input, and try to create the wallet. I won't guarantee this will work, but it's worth trying. There are still another options, but lets try this one first. Sorry for the inconvenience.

**Comment by lhszhh131421** [comment]
I try to do like you said ,but it failed.
My Seed Data of Decrypted mnemonic is 12 chinese words.
I cannot input the 12 chinese words in the Decrypted mnemonic or Decrypted seed hex.
So I cannot creat the wallet.

**Comment by jwjanus** [comment]
Oh, well. Now we have the reason :+1:  This problem has already occured. For now we support only english seed words. We plan to make it work with other languages in the near future, but for now, to restore you need to go through this path #7 
Let me know if it worked. Again, sorry for that.

**Comment by lhszhh131421** [comment]
I did it like you said.however,in the new window,it  always says establishing  RPC connection.
And It is always saying that for longer than 12 hours.
it is failed again.

**Comment by jwjanus** [comment]
If you create a new wallet does this look the same? We identified an issue related to "Establishing RPC connection", and we plan to fix it, but this is not necessarily associated with restoring process.

**Comment by lhszhh131421** [comment]
I choose  Restore Existing Wallet", click "Hex" on the upper right corner. Then paste BIP39 seed from 5th step. Then, create my  passphrase and click "Create Wallet". last,the new window  is always saying ”establishing RPC connection“ for longer than 20 hours!

**Comment by lhszhh131421** [comment]
when I create a brand new (not restored) wallet，also  not import key wallet.
the new windows is also says "establishing RPC connection" longer than 20 minutes.


![image002](https://user-images.githubusercontent.com/36321409/43961798-82774380-9ce8-11e8-83d6-0284ebb949de.jpg)

**Comment by jwjanus** [comment]
Application logs could help me with identifying the issue. On the screen above (upper right corner) there is "Logs" button. It should contain 1 or 2 rows ("exccd" and "exccwallet"), you can copy here last few lines from both rows

**Comment by lhszhh131421** [comment]
Ok,problem solved

**Comment by jwjanus** [comment]
Great to hear! Closing.
