### ISSUE TITLE
Can't buy ticket to vote

### ISSUE THREAD

**Issue by jayhoang06** [EXCCoin/exilibrium#22]
Hi team,
I'm using latest wallet version beta 7, I can view my asset but I can't buy ticket to vote. I could buy tickets in past but after I turned auto buy ticket on and turned it off, i can't buy tickets anymore. When i turn auto buy ticket, it not work so i turn it off to buy manually. I try to scan latest block and increase Expiry Blocks from 16 to 200 but no luck.
Please help me.
<img width="1218" alt="screen shot 2018-09-05 at 4 57 25 pm" src="https://user-images.githubusercontent.com/25931254/45211374-4f5eaa80-b2bc-11e8-98f3-7aa10c0c01cc.png">

**Comment by jwjanus** [comment]
Hi, thanks for creating the issue. Something like this could happen when blockchain is not fully synchronized although i see it probably was synced in your case. Before we'll investigate it further, please try to do a rescan (refresh icon in the bottom left corner). It's weird, but it could help for this.

**Comment by jayhoang06** [comment]
I try many times but still can't buy tickets
<img width="1201" alt="screen shot 2018-09-07 at 5 19 28 pm" src="https://user-images.githubusercontent.com/25931254/45213671-656f6980-b2c2-11e8-9280-1f917909c499.png">

**Comment by jwjanus** [comment]
Now, you can try resetting your stakepool connection. 

1. Above "Purchase" button there is a section with staking parameters. Click on the arrow on the right hand side - this should expand this box
2. Now you should see a "Stake Pool" select box, where you can choose a stakepool to connect to - click on the blue-ish button with lifebuoy icon.
3. Then you'll see "Configured Stake Pools" page - click on red "Remove" button and confim. You can restart the wallet now (it's not necessary).
4. Go to your selected stakepool - i see it's our official stakepool in your case. And log in to your account (important - it has to be the account you've previously configured with in Exilibrium)
5. Copy your API token (it's visible on "Settings" page), paste it to the wallet - now it goes as normal stakepool setup.
6. If it won't discover your previously bought tickets - restart should help.

This solution may help but it's not 100% sure. Sorry for the invonvenience.

**Comment by jayhoang06** [comment]
I try your solution but still can't purchase ticket, same error which I send above

**Comment by jwjanus** [comment]
Ok, i have another 2 possible solutions (they are independent from each other - you can try 2nd one first).

1. Close Exilibrium and open terminal on your machine (just type "terminal" in spotlight search - open the first app that appears). Type there this command:
`rm -rf ~/Library/Application\ Support/Exccd` and press Enter. 
You can close the terminal now. This operation deletes blockchain database. When you open Exilibrium again it should start downloading blockchain from the start.

2. Remove the wallet and restore it from mnemonic. You'll need to add stakepool connection again in that case. 

Sorry again for such complications. Let us know if it solved your problem.

**Comment by jayhoang06** [comment]
I have try solution 1 but still no help for this situation, but i finally can purchase a ticket. When i check all my wallet, i see i still have one transaction is pending so i rebroadcast it and after that, i can buy ticket. Maybe I got stuck with this transaction.
Thank you for your help.
