### ISSUE TITLE
problem importing wallet

### ISSUE THREAD

**Issue by furiamaf** [EXCCoin/exilibrium#26]
Hi, i have a problem on finilising my wallet transfer from copay wallet. I already went through the steps of decrypting the file and put the new passphrase but after that i only see a white page with no funds visible.

![screenshot 2018-09-20 09 14 21](https://user-images.githubusercontent.com/43434420/45804507-99805c80-bcbc-11e8-82bc-e647347a09f9.png)

**Comment by jwjanus** [comment]
Hi, i assume that your wallet mnemonic words were in italian. The problem has already occured for some people. Currently we only support english words in mnemonic, however we plan to add support for restoring them from different languages in the future. For now you have to go one level deeper to decode mnemonic into hex. Here are the instructions https://github.com/EXCCoin/exilibrium/issues/7#issuecomment-406899585 Please let us know, if it resolved your issue. Sorry, for the inconvenience.
