### ISSUE TITLE
I CANT WITHDRAW FROM MY WALLET

### ISSUE THREAD

**Issue by kessyjack2010** [EXCCoin/exilibrium#34]
I TRIED TO WITHDRAW FROM MY WALLET (22tqVqtVDELDiwNMUspjMtRUb5VwdMWZWKCh) BUT I CANT IT KEEP SHOWING ME MESSAGES 
![excc snip](https://user-images.githubusercontent.com/36675596/46731288-f4d9b500-cc92-11e8-8176-18e3444343ab.PNG)
![Uploading excc snip.PNG…]()
![excc snip msg](https://user-images.githubusercontent.com/36675596/46731380-2f435200-cc93-11e8-8476-39bac2fb82c3.PNG)

**Comment by jwjanus** [comment]
Hi @kessyjack2010 it's been almost 2 months since our chat, can you confirm that your issue was solved? You can just close the issue.
