### ISSUE TITLE
Import json not working 

### ISSUE THREAD

**Issue by Piradoxlanieve** [EXCCoin/exilibrium#7]
my wallet is not created,
I am following these steps.
https://support.excc.co/hc/en-us/articles/360006702912
Everything is correct but when I give to create wallet nothing happens,
My mnemonic decrypted are words in Spanish, this has something to do? so that my wallet is not restored?
sorry my bad english

**Comment by jwjanus** [comment]
Hi, thanks for creating first "historic" issue :1st_place_medal: sorry for the long response time.
Currently Exilibrium supports only english seed mnemonic words, however you can try to restore the wallet as follows:

1. Navigate to https://iancoleman.io/bip39/? title of the page should say "Mnemonic Code Converter"
2. Save the page using "Save as" option in your browser (or simply just use Ctrl+s).
3. When the page is saved as a file, go offline (**important** - stay offline for the rest of this process). Open this file in the browser.
4. Choose "12 words" instead "15 words", but without clicking "Generate" button. Type your seed words into "BIP39 Mnemonic" field.
5. You should see hexadecimal number in "BIP39 Seed" input field. Keep the file open.
6. Now, get back to the Exilibrium wallet. When selecting wallet creation type choose "Restore Existing Wallet", click "Hex" on the upper right corner.
7. Paste BIP39 seed from 5th step. Then, create your passphrase and click "Create Wallet".
8. If the wallet was restored correctly i recommend creating another one and transfering the funds to it. 
It would be easier for you to restore in the future. 

Hopefully everything goes well, but if your account balance after this procedure is "0.00" or anything else  happens, please let us know here. Sorry for the inconvenience.

**Comment by Piradoxlanieve** [comment]
Solved Thanks.

**Comment by furiamaf** [comment]
my mnemonic words were in italian, the problem was solved following your steps. Thanks
